# Generated by Django 4.2.10 on 2024-03-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_alter_produit_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('type_mouvement', models.CharField(max_length=50)),
            ],
        ),
    ]
