# Generated by Django 4.2.10 on 2024-03-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0004_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
